## **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 3: Descriptor Calculation**

PaDELPy is a Python wrapper for the PaDEL-Descriptor (molecular descriptor calculation) software.  

It provide the following descriptors/fingerprint:  
* 1444 - 2D Descriptors
* 431 - 3D Descriptors
* 881 bits - PubChem Fingerprints

## **Install PaDELpy**

In [1]:
!pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 54.7 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

## **Import libraries**

In [2]:
import pandas as pd
import numpy as np
from google.colab import files
from padelpy import padeldescriptor

## **Load dataset**

In [8]:
df = pd.read_csv('df_lipinski.csv')
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL66031,active,7.337242,Brc1cccc(Nc2ncnc3cc4[nH]cnc4cc23)c1,340.184,4.01220,2.0,4.0
1,CHEMBL553,active,7.714443,C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1,393.443,3.40510,1.0,7.0
2,CHEMBL137617,active,7.154902,C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1,357.215,4.54480,2.0,5.0
3,CHEMBL137189,active,6.698970,C/N=N/Nc1ccc2ncnc(Nc3cccc(C)c3)c2c1,292.346,4.09072,2.0,5.0
4,CHEMBL3353410,active,7.346787,C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...,499.619,4.50980,2.0,7.0

In [6]:
from google.colab import files

# This will open a file dialog for you to upload the file
uploaded = files.upload()

Saving df_lipinski.csv to df_lipinski.csv

In [9]:
data = df[['canonical_smiles', 'molecule_chembl_id']]
data.head()

                                    canonical_smiles molecule_chembl_id
0                Brc1cccc(Nc2ncnc3cc4[nH]cnc4cc23)c1        CHEMBL66031
1         C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1          CHEMBL553
2               C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1       CHEMBL137617
3                C/N=N/Nc1ccc2ncnc(Nc3cccc(C)c3)c2c1       CHEMBL137189
4  C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...      CHEMBL3353410

## **Convert to .smi format**

In [10]:
df_smi = data['canonical_smiles'].to_csv('smiles_chembl.smi', index=None, header=None)

In [11]:
! cat smiles_chembl.smi | head

Brc1cccc(Nc2ncnc3cc4[nH]cnc4cc23)c1
C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1
C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1
C/N=N/Nc1ccc2ncnc(Nc3cccc(C)c3)c2c1
C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C
C=CC(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1OCCCN1CCOCC1
CC(=O)N(C)/N=N/c1ccc2ncnc(Nc3cccc(C)c3)c2c1
CC(=O)OCN(C)/N=N/c1ccc2ncnc(Nc3cccc(Br)c3)c2c1
CC(C)(O)Cn1/c(=N/C(=O)c2ccnc(-c3ccccc3)c2)[nH]c2ccccc21
CCCCCCCCCCCCNC(=O)c1cc(NCc2cc(O)ccc2O)ccc1O

## **Calculate molecular Pubchem Fingerprints using "padeldescriptor" function**

In [12]:
padeldescriptor(mol_dir= "smiles_chembl.smi",
                d_file='pubchem_fingerprints.csv',
                fingerprints = True,
                retainorder= True,
                #removesalt = True, standardizetautomers = True, standardizenitro=True
                )

In [13]:
!ls -lh pubchem_fingerprints.csv

-rw-r--r-- 1 root root 144K Feb 21 11:02 pubchem_fingerprints.csv

In [14]:
df_fingerprint = pd.read_csv("pubchem_fingerprints.csv")
df_fingerprint.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_chembl_1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_chembl_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_chembl_3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_chembl_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_chembl_5,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Prepare Dataset for ML**

In [15]:
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL66031,active,7.337242,Brc1cccc(Nc2ncnc3cc4[nH]cnc4cc23)c1,340.184,4.01220,2.0,4.0
1,CHEMBL553,active,7.714443,C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1,393.443,3.40510,1.0,7.0
2,CHEMBL137617,active,7.154902,C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1,357.215,4.54480,2.0,5.0
3,CHEMBL137189,active,6.698970,C/N=N/Nc1ccc2ncnc(Nc3cccc(C)c3)c2c1,292.346,4.09072,2.0,5.0
4,CHEMBL3353410,active,7.346787,C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...,499.619,4.50980,2.0,7.0

In [16]:
# Select only the columns we need for ML
meta_cols = df[['molecule_chembl_id', 'bioactivity_class', 'pIC50']]

# Reset index to ensure proper alignment
meta_cols = meta_cols.reset_index(drop=True)
df_fingerprint = df_fingerprint.reset_index(drop=True)

# Combine meta data with fingerprints
combined_df = pd.concat([meta_cols, df_fingerprint.drop(df_fingerprint.columns[0], axis=1)], axis=1)

# Inspect the first few rows
combined_df.head()

,molecule_chembl_id,bioactivity_class,pIC50,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL66031,active,7.337242,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL553,active,7.714443,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL137617,active,7.154902,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL137189,active,6.698970,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL3353410,active,7.346787,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Save and download the dataset**

In [17]:
# Save as CSV
combined_df.to_csv("QSAR_dataset.csv", index=False)
print("Combined dataset saved as QSAR_dataset.csv")

# Download file in Colab
files.download("QSAR_dataset.csv")

Combined dataset saved as QSAR_dataset.csv

# **Calculate other fingerprints**

## **Download xml Files from Github**

In [18]:
!wget https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip

--2026-02-21 11:06:18--  https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip [following]
--2026-02-21 11:06:18--  https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘padel_descriptors_xml.zip’

padel_descriptors_x 100%[===================>]  10.62K  --.-KB/s    in 0s

2026-02-21 11:06:18 (58.3 MB/s) - ‘padel_descriptors_xml.zip’ saved [10871/10871]

## **Unzip all files**

In [19]:
!unzip padel_descriptors_xml.zip

Archive:  padel_descriptors_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

## **Calculate Fingerprints**

In [20]:
# Specify the XML file for SubstructureFingerprinter directly
Substruc_fp = "SubstructureFingerprinter.xml"

# Calculate Substructure fingerprints
padeldescriptor(
    mol_dir='smiles_chembl.smi',
    d_file='Substructure_fingerprints.csv',
    fingerprints=True,
    descriptortypes= Substruc_fp,
    retainorder=True
    # removesalt=True, standardizetautomers=True
)